### ISSUE TITLE
Could not determine container type!

### ISSUE THREAD

**Issue by 95Gman** [rebelvg/klpq_musicRadio#12]
![image](https://user-images.githubusercontent.com/74572009/207171399-f70bfb99-a482-4ec7-8fc0-ffcb3695b6df.png)
This is the error I get when I try to Generate Config. Not sure what it means. Can you make sense of it and tell me what I've missed?

**Comment by Manish-Yadav-Git** [comment]
You can close this ticket; the converter used in this case wasn't converting into the correct Vorbis type. If you see this error when you're configuring the config.cpp, it's likely due to a problem with how the file was created. Be sure to export to Ogg Vorbis :)
