### ISSUE TITLE
Error when adding radio to object

### ISSUE THREAD

**Issue by FistoGames** [rebelvg/klpq_musicRadio#2]
When adding the radio function to the speakers (small) object, it works in-game but I get this error still. 

USING THIS OBJECT INIT [this, false] call klpq_musicRadio_fnc_addRadio;

![20170611162814_1](https://user-images.githubusercontent.com/29359256/27014278-bf19b436-4ec3-11e7-8b45-81e61183a306.jpg)

**Comment by rebelvg** [comment]
What kind of object is this? Does it have dynamic simulation enabled? Is it a simple object? Does it have simulation enabled? Some cases above can cause this. I just tested it on latest stable arma and it works fine.

**Comment by mrpacman101** [comment]
i cannot confirm this issue or even saw others ( @rebelvg  love your work man! ). We are intensely using this mod in our group and everyone loves it, i wonder how it was driving convoys without awesome music 👍

**Comment by FistoGames** [comment]
not getting this error anymore thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
