### ISSUE TITLE
Adding Radio To An Object (No Turn Off Option)

### ISSUE THREAD

**Issue by Snak3Doc** [rebelvg/klpq_musicRadio#3]
Hi, Im having some issues adding the radio to an object, i put "[this, true] call klpq_musicRadio_fnc_addRadio;" into the init of the object and it adds the option to turn the radio on, but then it loses all ace interaction points and you cant turn it off.

Dedi Windows Server

**Comment by rebelvg** [comment]
Does it work in the singleplayer? I'll check later.

**Comment by rebelvg** [comment]
Just tested, can't confirm. Works fine on the dedicated server as usual. What object did you use? Some objects probably can't be used for that or some object states can interfere, like disabled simulation state.

**Comment by Snak3Doc** [comment]
Hmm ill try with some different objects, I was using the portable bluetooth speakers, ill dbl check the sim setting as well.

Edit: Its was disable simulation causing the turn off option to not show

**Comment by rebelvg** [comment]
Thanks for the confirmation. I think I can add some type of warning for objects with disabled simulation.

**Comment by Snak3Doc** [comment]
Yea it's odd cause I've got sim disabled on chairs with ace sitting  on them but it's arma lol
