### ISSUE TITLE
Listening to music walking

### ISSUE THREAD

**Issue by DominadorBR** [rebelvg/klpq_musicRadio#5]
![captura de tela 159](https://user-images.githubusercontent.com/18562379/39269676-dfe2e242-48a9-11e8-9acc-3321b50d68aa.png)

How to start songs the same is demonstrated in this part of the video (walking)?

Congratulations on your great work!!

**Comment by rebelvg** [comment]
It's a backpack radio, you can enable it in settings for the mod if playing in singleplayer or mission makers or server admins should enable it if you're playing multiplayer.
